server:
  port: 8001

spring:
  # 服务逻辑名称
  application:
    name: micro-service-consumer

  cloud:
    nacos:
      # 配置中心
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml

      # 注册中心
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
